# Generated by Django 5.2.8 on 2025-11-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, help_text='An estimated ending time (optional).', null=True)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['day', 'time'],
            },
        ),
    ]
