# Generated by Django 5.2.8 on 2025-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Elemento da Natureza',
                'verbose_name_plural': 'Elementos da Natureza',
                'ordering': ['name'],
            },
        ),
    ]
