# Generated by Django 5.2.8 on 2025-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_natureelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natureelement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='natureelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nature_elements/'),
        ),
    ]
