name: sergio-pacheco-backend
region: nyc
services:
  - name: api
    github:
      repo: viniciuseugenio/praca-sergio-pacheco
      branch: main
      deploy_on_push: true
    source_dir: /backend
    build_command: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    run_command: gunicorn --worker-tmp-dir /dev/shm --workers 2 --bind 0.0.0.0:8080 core.wsgi:application
    environment_slug: python
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET
      - key: ALLOWED_HOSTS
        value: ${APP_URL}
      - key: CORS_ALLOWED_ORIGINS
        value: ${CORS_ALLOWED_ORIGINS}
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: ACCESS_TOKEN_LIFETIME_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_LIFETIME_DAYS
        value: "7"
    routes:
      - path: /
databases:
  - name: db
    engine: PG
    version: "18"
    production: true
    cluster_name: sergio-pacheco-db
